# app/routes/tryon.py
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from pydantic import BaseModel
from app.database import get_db
from app.services.tryon_service import TryonService, PhotoNotFoundError, VtonProcessingError
from app.repositories.photo_repository import PhotoRepository
from app.repositories.result_repository import ResultRepository
from app.repositories.image_repository import ImageRepository
from app.repositories.upload_repository import UploadRepository

router = APIRouter(prefix="/tryon", tags=["tryon"])

# Dependency for TryonService
def get_tryon_service(db: Session = Depends(get_db)) -> TryonService:
    photo_repo = PhotoRepository(db)
    result_repo = ResultRepository(db)
    image_repo = ImageRepository(db)
    upload_repo = UploadRepository(db)
    return TryonService(photo_repo, result_repo, image_repo, upload_repo)

class TryonRequest(BaseModel):
    user_id: int
    person_photo_id: int
    cloth_photo_id: int

@router.post("")
def tryon(req: TryonRequest, tryon_service: TryonService = Depends(get_tryon_service)):
    try:
        result = tryon_service.create_tryon_result(
            user_id=req.user_id,
            person_photo_id=req.person_photo_id,
            cloth_photo_id=req.cloth_photo_id,
        )
        # result_url is now generated by the frontend or another service using the filename
        # but for consistency, we might want to return the Supabase public URL if possible, 
        # or just the filename as before. The frontend likely constructs the URL or calls an API to get it.
        # Let's stick to returning the filename and id as per previous contract, 
        # but update result_url to point to the public URL if we want to be helpful, 
        # or keep it abstract. 
        # The previous code returned `/results/image/{result.filename}` which implies a local route.
        # We should probably update this to be the full Supabase URL or keep it consistent with how other images are served.
        # Since we moved to Supabase, let's generate the public URL here using the image repo logic (although we don't have access to it easily here without another call).
        # Actually, the frontend might expect a specific format. Let's return the public URL.
        
        # However, to get the public URL, we need the ImageRepository or similar. 
        # Since we have tryon_service, maybe we can ask it? Or just construct it if we know the base URL.
        # But `tryon_service` has `image_repo`.
        
        # Let's simply return the filename and let the client handle it, OR return the full URL if we can.
        # The previous return was: "result_url": f"/results/image/{result.filename}"
        # This suggests there is a route that serves images. We should check if that route still works (it likely won't if it reads from disk).
        # We should probably update the return to be the supabase URL.
        
        return {
            "message": "합성 완료",
            "result_id": result.id,
            "result_filename": result.filename,
            # We'll leave the URL construction to the frontend or a dedicated 'get_url' endpoint 
            # effectively deprecating the local path logic.
            # But to be safe, let's try to provide a valid URL if possible.
            # For now, I will remove the potentially broken local URL and just return the filename.
             "result_filename": result.filename
        }
    except PhotoNotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except VtonProcessingError as e:
        raise HTTPException(status_code=500, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"가상 피팅 처리 중 오류 발생: {e}")